### ISSUE TITLE
Does not always move to top of listing

### ISSUE THREAD

**Issue by kuhnt** [chrispahm/gams-ide#7]
Check box "move to end of listing after solve" is disabled. After solving the model and having e.g. a compilation error, I sometimes end up in the middle of the listing and not in the beginning where I see the relevant errors. Sometimes it works, but I have not found a pattern for this bug yet.

**Comment by chrispahm** [comment]
Right now, there are 3 settings influencing how and where the LST is opened:
<img width="782" alt="image" src="https://github.com/chrispahm/gams-ide/assets/20703207/c5bc92e9-0846-4092-83d4-0634db085537">

1) "jumpToAbort": If set to true, will jump to the first abort statement encountered. This has top priority over the other settings
2) "defaultParameterToJumpToAfterSolve": E.g. p_sumRes, will jump to the last position of the parameter if it is found in the LST
3) "autoScrollToEndOfListing": If none of the two previous settings returned a line where the LST should be openend, it will automatically try to scroll to the LST. 

We need to check if there is an abort statement or a reference to the "defaultParameterToJumpToAfterSolve" in cases where the LST is scrolled to the middle. Otherwise we need to narrow down when the bug occurs.

Another option would be to have a setting: "scroll to top if compilation errors are found"

**Comment by chrispahm** [comment]
Decided to implement "Scroll to top on compilation errors"

**Comment by chrispahm** [comment]
Implemented in 296ff29, please re-open if issue persists
